config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener'

  devise_for :users, controllers: { registrations: "registrations" }
  resources :categories, only: [:index, :new, :create, :destroy]
  resources :users do
    resources :categories do 
      resources :budgets, only: [:index, :show, :new, :create, :update, :destroy]
      resources :expenses, only: [:index, :show, :new, :create, :destroy]
    end
  end
  
  resources :categories do 
    resources :expenses, only: [:index, :show, :new, :create, :destroy]
  end

  # Define any other custom routes you need here
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  # class methods and attributes here
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :budget_categories, class_name: 'BudgetCategory', foreign_key: 'budget_id', dependent: :destroy
  has_many :categories, through: :budget_categories

  validates :name, presence: true, length: { maximum: 255 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expense_categories, dependent: :destroy
  has_many :expenses, through: :expense_categories, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 255 }
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :categories, join_table: 'expense_categories', dependent: :destroy
  validates :name, presence: true, length: { maximum: 255 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
  belongs_to :expense, class_name: 'Expense'
  belongs_to :category, class_name: 'Category'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # class methods and attributes here
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :budgets
  has_many :categories, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:index]

  def after_sign_in_path_for(_resource)
    user_categories_path(current_user)
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name bio password password_confirmation])
  end

  def devise_controller?
    devise_controller_names.include?(controller_name)
  end

  def devise_controller_names
    %w[registrations sessions passwords confirmations unlocks]
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(author_id: current_user.id)
    @total_amount = @categories.joins(:expenses).sum(:amount)
  end

  def new
    @user = current_user
    @category = Category.new
  end

  def create
    @user = current_user
    @category = Category.new(category_params.merge(author_id: current_user.id))

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    other_category = Category.where.not(id: @category.id).first # choose another valid category to assign expenses to

    Expense.where(category_id: @category.id)
      .update_all(category_id: other_category&.id) # assigns the expenses to the other category
    @category.destroy
    redirect_to categories_path
  end

  def total_amount_for_category(category)
    category.expenses.sum(:amount)
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(created_at: :desc) # sort expenses by most recent
    @total_expense = @expenses.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @categories = current_user.categories
    @expense = Expense.new
  end

  def create
    @category = Category.find(params[:category_id])
    @expense = Expense.new(expense_params)

    # set the category for the new expense
    @expense.category = @category

    # assign an array of category ids to the expense object
    @expense.category_ids = params[:expense][:category_ids]

    if @expense.save
      redirect_to category_expenses_path(@category)
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @expense = @category.expenses.find(params[:id])

    # Remove the expense from the categories association
    @expense.categories.delete(@category)

    # Destroy the expense record if it's not associated with any other categories
    @expense.destroy if @expense.categories.empty?

    redirect_to category_expenses_path(@category)
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id, category_ids: [])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(_resource)
    new_user_session_path
  end

  def after_sign_up_path_for(resource)
    devise_path(resource)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    # render your splash page (app/views/pages/splash.html.erb)
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def show
    if params[:id] == 'sign_out'
      sign_out_and_redirect
    else
      find_user
    end
  end

  private

  def sign_out_and_redirect
    sign_out current_user
    redirect_to new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
  <div class="category-details my-4 flex flex-col bg-white overflow-x-auto py-2 category-card items-end">
<%= link_to category_expenses_path(category), class: "category-card" do %>
    <div class="flex justify-between w-screen px-2">
      <div class="flex card">
        <!-- image -->
      <div>
        <% if category.icon.present? %>
          <% if category.icon.start_with?("https://") %>
            <%= image_tag category.icon, height: '80px', width: '70px' %>
          <% else %>
            <% if Rails.application.assets.find_asset("#{category.icon}.png") || Rails.application.assets.find_asset("#{category.icon}.jpg") %>
              <%= image_tag asset_path("#{category.icon}"), height: '80px', width: '70px' %>
            <% else %>
               <%= image_tag "default.png", height: '80px', width: '70px' %>
            <% end %>
         <% end %>
        <% end %>
      </div>

        <!-- information -->
        <div class="ml-4 flex card flex-col justify-between">
          <div class="flex justify-between">
            <h4 class="text-gray-500 text-2xl"><%= category.name %></h4>
            <div class="text-gray-800"><%=  controller.total_amount_for_category(category) %> $</div>
          </div>

          <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">
          <h4 class="text-gray-500 text-sm"><%= category.created_at.strftime('%B %d, %Y')  %></h4>
        </div>
      </div>
    </div>
<% end %>
    <div class="mt-4">
      <% if category.author_id == current_user.id %>
      <%= button_to 'Delete', user_category_path(current_user, category), method: :delete, data: { confirm: 'Are you sure?' }, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4" %>
      <% end %>
    </div>
  </div>

app/views/categories/index.html.erb
<div class="text-white h-screen">
  <div class="flex py-8 justify-between background items-center h-10 px-4 w-full">
    <svg class="h-8 w-8 text-white"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
    </svg>
    <h1 class="text-center background text-2xl">CATEGORIES</h1>
    <svg class="h-8 w-8 text-white"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
    </svg>
<div class="sign_out_button">
   <button class=" text-white font-semibold text-lg">
     <%= link_to 'Sign out',  destroy_user_session_path, method: :delete %>
   </button>
 </div>
    
</div>
<% if @categories.any? %>
  <div class="categories-list flex flex-col justify-center bg-slate-100 items-center w-full">
  <div class="bg-white category-card overflow-auto py-4 flex justify-between">
    <p class="text-gray-500">Total amount: </p>
    <p class="text-gray-800"><%=  @total_amount %> $</p>
  </div>
    <% @categories.each do |category| %>
      <%= render 'category', category: category %>
    <% end %>
  </div>
<% else %>
  <p>No categories found.</p>
<% end %>
  <a href="<%=  new_user_category_path(current_user) %>" class="my-4 shadow-md  bg-blue-200 hover:bg-blue-500 text-blue-900 font-semibold hover:text-white py-2 px-4 block border rounded">
    <button class="w-full focus:outline-none">Add a new category</button>
  </a>
</div>

app/views/categories/new.html.erb
<div class="flex px-2 py-8 text-white background items-center h-10 px-4 w-full">
    <svg class="h-8 w-8 text-white-500"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />  <line x1="12" y1="8" x2="12" y2="16" />  <line x1="8" y1="12" x2="16" y2="12" /></svg>
    <h1 class="ml-4 text-center background text-2xl">New Category</h1>
</div>
<div class="flex flex-col">
<%= form_with model: [@user, @category], url: user_categories_path(@user) do |form| %>
<div class="flex my-2 mx-2">
  <%= form.label :name, class:"form-label" %>
  <%= form.text_field :name, placeholder: "Full name", class:"border form-input" %>
</div>
<div class="flex my-2 mx-2">
  <%= form.label :icon, class:"form-label" %>
  <%= form.text_field :icon, placeholder: "Icon name | url", class:"border form-input"%>
</div>
  <%= form.submit "Create Category", class:"bg-blue-200 shadow-md w-full focus:outline-none my-4 bg-white hover:bg-blue-500 text-blue-900 font-semibold hover:text-white py-2 px-4 block border rounded" %>
<% end %>
  <a href="<%=  user_categories_path(current_user) %>" class="shadow-md w-full focus:outline-none my-2 bg-white hover:bg-red-500 text-red-900 font-semibold hover:text-white py-2 px-4 block border rounded">
    <button class="w-full focus:outline-none">Back</button>
  </a>
</div>

app/views/expenses/_expense.html.erb
<div class="category-details my-4 flex flex-col bg-white overflow-x-auto py-2 category-card items-end">
  <div class="flex justify-between w-screen px-2">
    <div class="ml-4 flex card flex-col justify-between">
      <div class="flex justify-between items-center">
        <h4 class="text-gray-500 text-2xl"><%= expense.name %></h4>
        <div class="text-gray-800">Amount: <%= expense.amount %> $</div>
      </div>
      <hr class="h-px my-10 bg-gray-200 border-0 dark:bg-gray-700">
      <h4 class="text-gray-500 text-sm"><%= expense.created_at.strftime('%B %d, %Y')  %></h4>
    </div>
  </div>
<% if category.author_id == current_user.id %>
  <%= button_to 'Delete', category_expense_path(category, expense), method: :delete, data: { confirm: 'Are you sure?' }, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4", params: { category_id: category.id } %>
<% end %>
</div>

app/views/expenses/index.html.erb
<div class="text-white h-screen">
  <div class="flex py-8 justify-between background items-center h-10 px-4 w-full">
    <svg class="h-8 w-8 text-white"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
    </svg>
    <h1 class="text-center background text-2xl">Expenses for <%= @category.name %></h1>
    <svg class="h-8 w-8 text-white"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
    </svg>
</div>
<% if @expenses.any? %>
  <div class="categories-list flex flex-col justify-center bg-slate-100 items-center w-screen">
  <div class="bg-white category-card overflow-auto py-4 flex justify-between">
    <p class="text-gray-500">Total amount: </p>
    <p class="text-gray-800"><%=  @total_expense %> $</p>
  </div>
<% puts "@expenses count before rendering: #{@expenses.count}" %>
<% @expenses.each do |expense| %>
  <%= render 'expense', expense: expense, category: @category %>
<% end %>
<% puts "@expenses count after rendering: #{@expenses.count}" %>
  
</div>
<% else %>
<p>No expenses found.</p>
<% end %>
  <a href="<%= new_category_expense_path(@category) %>" class="my-4 shadow-md  bg-blue-200 hover:bg-blue-500 text-blue-900 w-screen font-semibold hover:text-white py-2 px-4 block border rounded">
    <button class="w-full focus:outline-none">Add a new Expense</button>
  </a>
    <a href="<%=  user_categories_path(current_user) %>" class="shadow-md w-full focus:outline-none my-2 bg-white hover:bg-red-500 text-red-900 font-semibold hover:text-white py-2 px-4 block border rounded">
    <button class="w-full focus:outline-none">Back</button>
  </a>
</div>
</div>

app/views/expenses/new.html.erb
<div class="flex py-8 text-white background items-center h-10 px-4 w-full">
    <svg class="h-8 w-8 text-white-500"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />  <line x1="12" y1="8" x2="12" y2="16" />  <line x1="8" y1="12" x2="16" y2="12" /></svg>
    <h1 class="ml-4 text-center background text-2xl">Create a new Expense</h1>
</div>
<div class="flex flex-col">
<%= form_with(model: [@category, @expense], url: category_expenses_path(@category)) do |form| %>
  <div class="flex my-2 mx-2">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, placeholder: "Full name", class:"border form-input" %>
  </div>
  <div class="flex my-2 mx-2">
    <%= form.label :amount, class:"form-label" %>
    <%= form.number_field :amount, placeholder: "Amount($)", class:"border form-input"%>
  </div>
  <div style="margin:1rem;" >
  <%= form.label :category_ids,class:"form-label"%>
  All Categories: <%= form.collection_check_boxes :category_ids, current_user.categories, :id, :name %>
  </div>
  <%= form.submit "Save Expense", class:"bg-blue-200 shadow-md w-full focus:outline-none my-4 bg-transparent hover:bg-blue-500 text-blue-900 font-semibold hover:text-white py-2 px-4 block border rounded" %>
<% end %>
  <a href="<%=  user_categories_path(current_user) %>" class="shadow-md w-full focus:outline-none my-2 bg-transparent hover:bg-red-500 text-red-900 font-semibold hover:text-white py-2 px-4 block border rounded">
    <button class="w-full focus:outline-none">Back</button>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgetapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application.tailwind", media: "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen w-full">
    <% if notice %>
      <p class="alert"><%= notice %></p>
    <% end %>
    <main class="h-screen">
      <%= yield %>
    </main>
  </body>
</html>

app/views/splash/index.html.erb
<div class=" flex flex-col text-center justify-between bg-neutral-100	h-screen items-center">
  <h1 class="text-black h-screen flex items-center splash-text text-7xl font-bold font-mono my-2">costino!</h1>
  <div class= "flex flex-col sm:text-center text-center justify-end py-4">
    <a href="<%= new_user_session_path() %>" class="w-screen flex text-lg justify-center my-4 bg-transparent hover:bg-blue-500 text-gray-400 font-semibold hover:text-white py-2 px-4">
      <button class=" focus:outline-none">LOG IN</button>
    </a>
    <a href="<%= new_user_registration_path() %>" class="w-screen flex text-lg justify-center my-4 bg-transparent hover:bg-blue-500 text-gray-400 font-semibold hover:text-white py-2 px-4">
      <button class=" focus:outline-none">SIGN UP</button>
    </a>
  </div>
<div>